[package]
name = "mns-supervisor"
version = "0.1.0"
authors = ["Michael Allwright <allsey87@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.4"
structopt = { version = "0.3", default-features = false }
tokio = { version = "0.2", features = ["full"] }

