[package]
name = "mns-gui"
version = "0.1.0"
authors = ["Michael Allwright <allsey87@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "0.5.4" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "0.2", features = ["full"] }
futures = { version = "0.3.5", default-features = false }
warp = { version = "0.2", features = ["websocket"] }
uuid = { version = "0.8", features = ["serde", "v4"] }